module.exports={
    verifyLogin:(req,res,next)=>{
       if(req.session.adminloggedIn){
           next()
       }else{
        console.log("spspsps");
           res.redirect('/admin/admin-login')
       }
   }
}
